// <auto-generated />
using IS_Employee_Tracker.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IS_Employee_Tracker.Migrations
{
    [DbContext(typeof(EmployeeTrackerContext))]
    [Migration("20221026021744_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.30");

            modelBuilder.Entity("IS_Employee_Tracker.Models.EmployeeInfo", b =>
                {
                    b.Property<string>("BYUID")
                        .HasColumnType("TEXT");

                    b.Property<string>("BYUName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmpRecordNum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExpectedWorkHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FormSubmitted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<bool>("GradTuition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("IncreaseInputDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("International")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastPayIncrease")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NameChangeComplete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<double>("PayIncreaseAmount")
                        .HasColumnType("REAL");

                    b.Property<double>("PayRate")
                        .HasColumnType("REAL");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("PositionType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Semester")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupervisorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SurveySent")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Terminated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TerminationDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WorkAuthorization")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkAuthorizationEmailSent")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YearInProgram")
                        .HasColumnType("TEXT");

                    b.HasKey("BYUID");

                    b.ToTable("Information");

                    b.HasData(
                        new
                        {
                            BYUID = "665614397",
                            BYUName = "Scott, Michael",
                            ClassCode = "26077",
                            EmailAddress = "Michael.Scott@dundermifflin.fake",
                            EmpRecordNum = 0,
                            ExpectedWorkHours = 20,
                            FirstName = "Michael",
                            FormSubmitted = true,
                            Gender = "Male",
                            GradTuition = true,
                            HireDate = "1/3/2020",
                            IncreaseInputDate = "6/27/2021",
                            International = false,
                            LastName = "Scott",
                            LastPayIncrease = "2/27/2021",
                            NameChangeComplete = true,
                            Notes = "",
                            PayIncreaseAmount = 0.25,
                            PayRate = 15.5,
                            Phone = "(888)867-5309",
                            PositionType = "TA IS 201",
                            Semester = "Fall",
                            SubmissionDate = "1/3/2020",
                            SupervisorName = "David Wallace",
                            SurveySent = "Sent",
                            Terminated = false,
                            TerminationDate = "",
                            WorkAuthorization = true,
                            WorkAuthorizationEmailSent = "1/4/2020",
                            Year = 2020,
                            YearInProgram = "MSB Core (IS or other)"
                        },
                        new
                        {
                            BYUID = "341054778",
                            BYUName = "Schrute, Dwight",
                            ClassCode = "27432",
                            EmailAddress = "Dwight.Schrute@dundermifflin.fake",
                            EmpRecordNum = 1,
                            ExpectedWorkHours = 20,
                            FirstName = "Dwight",
                            FormSubmitted = true,
                            Gender = "Male",
                            GradTuition = true,
                            HireDate = "1/4/2022",
                            IncreaseInputDate = "6/30/2022",
                            International = false,
                            LastName = "Schrute",
                            LastPayIncrease = "6/30/2022",
                            NameChangeComplete = true,
                            Notes = "",
                            PayIncreaseAmount = 0.25,
                            PayRate = 15.5,
                            Phone = "(888)867-5310",
                            PositionType = "RA",
                            Semester = "Winter",
                            SubmissionDate = "1/4/2022",
                            SupervisorName = "Michael Scott",
                            SurveySent = "Sent",
                            Terminated = false,
                            TerminationDate = "",
                            WorkAuthorization = true,
                            WorkAuthorizationEmailSent = "1/5/2022",
                            Year = 2022,
                            YearInProgram = "MISM"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
